S135 GCP update for Asana, Dropbox and bulk
Worklytics/psoxy pull request #211
Opened 2022-11-10 22:48 UTC by aperez-worklytics

Updated GCP example to include specs variables and secrets:
- Better handling of default secrets (Salt and PseudonymKey, this one wasn't included)
- Support for OAuth access/refresh tokens, like Asana or Dropbox
- Added `SecretManager` support for update secrets

End-to-end tested with Asana, Dropbox and bulk connectors.

**NOTE** https://github.com/Worklytics/psoxy/pull/151 will be closed as it was out-of-date and not valid with latest changes on how connector specs work

### Features
[> paste links to issues/tasks in project management
 - []()](https://app.asana.com/0/1203255538501504/1202951314447003)

### Change implications

 - dependencies added/changed? **yes**
   - to support `SecretManager` is required to use [bom libraries](https://cloud.google.com/secret-manager/docs/reference/libraries); otherwise you will get very weird errors during its usage (like internals settings not provided, etc).
   - For that reason, now `google-cloud-storage` uses bom version instead of a specific one.

2022-11-10 22:55 UTC, aperez-worklytics commented on infra/modular-examples/gcp-google-workspace/main.tf
> +  }, module.psoxy-gcp.secrets)
Now any secrets from `gcp` module are added here instead of being provided as parameter separately

2022-11-10 22:55 UTC, aperez-worklytics commented on infra/modular-examples/gcp-google-workspace/main.tf
> +  k => [for secret in spec.secured_variables : "${k}.${secret.name}"]
Following AWS approach

2022-11-10 22:55 UTC, aperez-worklytics commented on infra/modules/gcp-oauth-long-access-strategy/README.md
> -Infra to support `OAuthAccessTokenSourceAuthStrategy` for a gcp psoxy instance.
This module and the other one for refresh token weren't used and with the new one, not valid anymore.

2022-11-10 22:55 UTC, aperez-worklytics commented on java/impl/gcp/src/main/java/co/worklytics/psoxy/CloudFunctionRequest.java
> +            body = request.getInputStream() != null ? request.getInputStream().readAllBytes() : null;
Coming from https://github.com/Worklytics/psoxy/pull/151; to properly handle a body in request/response. Mainly for Dropbox.

2022-11-10 22:55 UTC, aperez-worklytics commented on java/impl/gcp/src/main/java/co/worklytics/psoxy/GcpModule.java
> +        return new SecretManagerConfigService(null, ServiceOptions.getDefaultProjectId(), Duration.ofMinutes(20));
`ServiceOptions.getDefaultProjectId()` is a built-in method from GCP cloud functions framework to provide the `id` of the project. We need that to build the secret names, which could be created using the project id (my-project) or the project number (1234)

2022-11-10 22:55 UTC, aperez-worklytics commented on java/impl/gcp/src/main/java/co/worklytics/psoxy/Route.java
> +        if (abstractResponse.getBody() != null) {
Again, coming from https://github.com/Worklytics/psoxy/pull/151

2022-11-28 19:16 UTC, eschultink requested changes
a couple things look to me like breaking changes.  should ideally avoid that and certainly comment in CHANGELOG.

2022-11-28 19:16 UTC, eschultink commented on infra/modules/gcp-psoxy-rest/variables.tf
> -
so this is breaking change, right? for anyone invoking `gcp-psoxy-rest` module directly, they'll need to stop passing these, right?

if so, 1) add to `CHANGELOG` and 2) possibly leave these in `variables.tf`, just mark as deprecated?

2022-11-28 19:16 UTC, eschultink commented on infra/modules/gcp/main.tf
> -}
also potentially breaking change, right? could maintain this to keep interface consistent (mark as deprecated, and we can remove in in `v0.5.x`

2022-11-28 19:16 UTC, eschultink commented on java/impl/gcp/src/main/java/co/worklytics/psoxy/SecretManagerConfigService.java
> +    final Duration defaultTtl;
`@NonNull`s on these? (maybe doesn't matter for `namespace`, but presumably others can't be `null`

2022-12-01 19:44 UTC, aperez-worklytics commented on java/core/src/main/java/co/worklytics/psoxy/rules/asana/PrebuiltSanitizerRules.java
> +            "sort_ascending",
From https://github.com/Worklytics/psoxy/pull/214 (merged to main, instead of RC)

2022-12-01 19:44 UTC, aperez-worklytics commented on java/core/src/main/resources/rules/asana/asana.yaml
> +      - "opt_fields"
From https://github.com/Worklytics/psoxy/pull/214 (merged to main, instead of RC)

2022-12-07 20:04 UTC, merged