S111 more api tests
Worklytics/psoxy pull request #35
Opened 2021-12-02 17:38 UTC by eschultink

More testing; no actual logic changes, so not urgent to actually get this merged.  It just validates that strengthened rules aren't blocking anything that we need in practice (eg, retrieval of subsequent pages).

### Features
  - more test coverage that rules allow query params, which is needed to support paging
  - more test coverage that rules allow/block expected url variants 

### Change implications

 - dependencies added/changed? **no**

2021-12-03 10:55 UTC, aperez-worklytics approved these changes

2021-12-03 20:29 UTC, jlorper requested changes
I'd do tests a little bit more readable so "garbage" used is more explicit

2021-12-03 20:29 UTC, jlorper commented on java/core/src/test/java/co/worklytics/psoxy/rules/RulesBaseTestCase.java
> +        assertTrue(sanitizer.isAllowed(new URL(url + "/asdfasdf/asdfasdf")), "multiple params blocked");
Improve readability and nicer for OSS project. Same below.

```suggestion
        assertTrue(sanitizer.isAllowed(new URL(url + "/anypath")), "path blocked");
        assertTrue(sanitizer.isAllowed(new URL(url + "/anypath/anysubpath")), "path with subpath blocked");
```

2021-12-03 20:29 UTC, jlorper commented on java/core/src/test/java/co/worklytics/psoxy/rules/RulesBaseTestCase.java
> +        assertFalse(sanitizer.isAllowed(new URL(url)), "rules allowed url that should be blcoked: " + url);
```suggestion
        assertFalse(sanitizer.isAllowed(new URL(url)), "rules allowed url that should be blocked: " + url);
```

2021-12-03 20:29 UTC, jlorper commented on java/core/src/test/java/co/worklytics/psoxy/rules/google/DirectoryTests.java
> +        String groupEndpoint = "https://admin.googleapis.com/admin/directory/v1/groups/asdfas";
```suggestion
        String groupEndpoint = "https://admin.googleapis.com/admin/directory/v1/groups/an-arbitrary-subresource";
```

2021-12-03 20:29 UTC, jlorper commented on java/core/src/test/java/co/worklytics/psoxy/rules/google/GDriveTests.java
> +        String endpoint = "http://www.googleapis.com/drive/v2/files/Asdfasdfas/revisions";
replace "Asdfasdfas" with something more readable

2021-12-17 00:18 UTC, jlorper approved these changes

2021-12-17 00:18 UTC, jlorper commented on java/core/src/test/java/co/worklytics/psoxy/rules/google/DirectoryTests.java
> +        String membersEndpoint = "https://admin.googleapis.com/admin/directory/v1/groups/asdfas/members";
```suggestion
        String membersEndpoint = "https://admin.googleapis.com/admin/directory/v1/groups/any-group-id/members";
```

2021-12-17 00:18 UTC, jlorper commented on java/core/src/test/java/co/worklytics/psoxy/rules/RulesBaseTestCase.java
> +        assertTrue(sanitizer.isAllowed(new URL(url + "/anypath/anysubpath")), "2 subpathes allowed");
```suggestion
        assertTrue(sanitizer.isAllowed(new URL(url + "/anypath/anysubpath")), "2 subpaths allowed");
```

2021-12-23 22:24 UTC, merged