some broken doc links
Worklytics/psoxy pull request #553
Opened 2023-09-29 19:45 UTC by eschultink

### Fixes
 - broken docs links

### Change implications

 - dependencies added/changed? **no**
 - something to note in `CHANGELOG.md`? **no**

2023-10-02 10:01 UTC, aperez-worklytics requested changes

2023-10-02 10:01 UTC, aperez-worklytics commented on README.md
> +| Jira Cloud _alpha_                | [docs/sources/atlassian/jira-cloud](docs/sources/atlassian/jira/jira-cloud.md)   | "Classic Scopes": `read:jira-user` `read:jira-work` "Granular Scopes": `read:g
Current doc for cloud points to `README`; the one for server is fine.

```suggestion
| Jira Cloud _alpha_                | [docs/sources/atlassian/jira-cloud](docs/sources/atlassian/jira/README.md)   | "Classic Scopes": `read:jira-user` `read:jira-work` "Granular Scopes": `read:group:jira` `read:user:jira`  "User Identity API" `read:account` |
```

Maybe we could move *current* readme content to `jira-cloud.md` and put as `README` just the index with links to `jira-cloud.md` and `jira-server.md` ?

2023-10-02 22:26 UTC, eschultink commented
@aperez-worklytics - thanks for catching that; I thought there was one for both. I think OK for now.

2023-10-03 09:10 UTC, aperez-worklytics approved these changes

2023-10-03 20:28 UTC, merged