Include external todos for MSFT connectors
Worklytics/psoxy pull request #695
Opened 2024-04-02 16:11 UTC by aperez-worklytics

Fixed doc generation for 1st step. On MSFT connectors, external_todo was ignored as it was populated by module `azuread-grant-all-users` for listing the permissions to add

### Fixes
[External todos are not generated for MSFT](https://app.asana.com/0/1201039336231823/1206092206362748)

### Features
> paste links to issues/tasks in project management
 - []()

### Change implications

 - dependencies added/changed? **no**
 - something important to note in future release notes?
   - NOTE in `CHANGELOG.md` anything that will show up in `terraform plan`/`apply` that isn't
     obviously a no-op? **no**
   - breaking changes? **no** if in module/example that is NOT marked `alpha`, requires major version
     change

2024-04-02 16:14 UTC, aperez-worklytics commented on infra/modules/worklytics-connectors-msft-365/main.tf
> +  content  = format("%s\n## Setup\nThen, please follow next instructions for complete the setup: \n\n%s", module.msft_365_grants[each.key].todo, each.value.external_token_todo)
Using this as an override of the current file generated by `msft_365_grants` module, only if the connector has a todo to append. ATM, Teams is the only one having this.

2024-04-02 20:48 UTC, eschultink requested changes

2024-04-03 17:59 UTC, aperez-worklytics commented on infra/modules/worklytics-connectors-msft-365/main.tf
> +resource "local_file" "todo-with-external-todo" {
Cool, thanks

2024-04-03 19:04 UTC, eschultink approved these changes

2024-04-03 19:04 UTC, eschultink commented on infra/modules/worklytics-connectors-msft-365/main.tf
> +  todos_to_populate = { for k, v in module.worklytics_connector_specs.enabled_msft_365_connectors : k => v if try(v.external_token_todo != null, false) && var.todos_as_local_files }
ok for now; kinda weird to do it inside the loop, instead of just once (as it should be same)

2024-04-03 19:04 UTC, merged