env var only config
Worklytics/psoxy pull request #823
Opened 2024-10-09 22:17 UTC by eschultink

### Features
  - only allow some config as env vars

### Change implications

 - dependencies added/changed? **no**
 - something important to note in future release notes? **Yes**
   - NOTE in `CHANGELOG.md` anything that will show up in `terraform plan`/`apply` that isn't
     obviously a no-op? **if anyone is depending on overriding env vars with secrets/parameter store, this will break that**
   - breaking changes? if in module/example that is NOT marked `alpha`, requires major version
     change

2024-10-10 16:56 UTC, jlorper commented on java/core/src/test/java/co/worklytics/psoxy/gateway/ProxyConfigPropertyTest.java
> +    public void remoteConfigVars(String paramName) {
:red_circle: missing test body

2024-10-10 17:00 UTC, jlorper requested changes
missing test body

2024-10-10 17:00 UTC, jlorper commented on java/impl/gcp/src/main/java/co/worklytics/psoxy/SecretManagerConfigService.java
> +        if (property.isEnvVarOnly()) {
Tip: I like preconditions for these kind of checks.
`Preconditions.checkArgument(!property.isEnvVarOnly(), "Can't put env-only config property: " + property);`

2024-10-14 10:03 UTC, aperez-worklytics approved these changes
OK after @jlorper changes

2024-10-21 21:03 UTC, jlorper approved these changes

2024-10-23 20:01 UTC, merged